### ISSUE TITLE
关于魔改库的随机头图方法

### ISSUE THREAD

**Issue by Jerry-FaGe** [Dreamy-TZK/StaticFile_Hexo#1]
魔改库173行左右的随机头图方法，在我的浏览器会报 TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Arguments.o (<anonymous>:1:83) ，取到的arguments.length值为false，所以直接走 < 4的那个分支了。百度了一下是什么严格模式语法问题，本人不太懂JS希望大佬指教

**Comment by Dreamy-TZK** [comment]
已放弃维护
